### ISSUE TITLE
Add integration testing for python CLI client

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/client-python#3] opened 2020-07-13 10:32 UTC
This could be done against a fake HTTP server. 
Faster implementation (slower tests) could be achieved with testing against a live cluster.

**Comment by mikalstill** [comment] 2021-02-12 20:08
This is a duplicate of https://github.com/shakenfist/shakenfist/issues/540.

**Closed by mikalstill** 2021-02-12 20:08 UTC
